### ISSUE TITLE
Usage文档中的几个问题

### ISSUE THREAD

**Issue by hopeful0** [yunify/qingstor-sdk-java#3]
### [Configuration Guide](https://github.com/yunify/qingstor-sdk-java/blob/master/docs/configuration.md)

**问题**：“Code Snippet"中的"Create API server"中`moreEvn.setHost("privatestor.com")`
 使用该配置会导致调用API时出现错误：`SEVERE: privatestor.com: unknown error`

**修改意见**：修改参数
`moreEvn.setHost("qingstor.com")`

---

**问题**："Code Snippet"中的"Create API server"中`moreEvn.setPort(443)` 参数类型错误

修改意见：修改参数为String类型
`moreEvn.setPort("443")`

### [QingStor Service Usage Guide](https://github.com/yunify/qingstor-sdk-java/blob/master/docs/qingstor_service_usage.md)

**问题**:文档中"Code Snippet"中的"Initialize the QingStor service with a configuration"中`QingStor storService = new QingStor(evn, bucketName);` 没有对应的构造函数。

**修改意见**:使用正确的构造函数
`QingStor storService = new QingStor(evn);`
或
``` java
String zoneName = "pek3a";
QingStor storService = new QingStor(evn, zoneName);
```

**Comment by karoosnip** [comment]
抱歉，这个会及时调整

**Comment by karoosnip** [comment]
你好，发的这个几个建议我已经调整了
