### ISSUE TITLE
API——Get Bucket ACL、Put Object、Delete Object的问题

### ISSUE THREAD

**Issue by hopeful0** [yunify/qingstor-sdk-java#5]
下面是具体的问题：

1. **Get Bucket ACL** 得到的结果中 `owner`的`name` 和 `默认ACLGrantee`的`name` 都是 `""`。
2. **Put Object** `input.setContentLength(size)`好像没有什么用处。当objectName设为`""`时返回`409:The bucket you are trying to create already exists.`这个接口不应该有这样的功能吧。
3. **Delete Object** 当objectName设为`""`时返回`409:The bucket is not empty.`这个接口不应该有这样的功能吧。当object不存在时返回与删除成功同样的结果，无法判断。

**Comment by karoosnip** [comment]
你好，1、默认情况下name的值是为空的;
2、objectName的名称我们会加上限制
3、409这个和ObjectName为空有关，我们会加上限制；如果对删除的文件不确定，可以先optionsObject，看下文件的状态

**Comment by hopeful0** [comment]
1.在其他接口中这个name都有值（默认好像是用户名），只有这个接口没有。不过不会产生什么问题。
3.409的原因应当是：当objectName为`""`时，bucket被当做object操作了，我认为这是不合理的。

**Comment by karoosnip** [comment]
你好，objectName现在加上“” 的validate了，应该不会出现你说的问题了
