### ISSUE TITLE
异步问题

### ISSUE THREAD

**Issue by hopeful0** [yunify/qingstor-sdk-java#6]
如果使用了一个异步接口，即时回调已经被调用，线程（程序）也不会停止。

建议当回调被调用后关闭停止连接池线程。（或者给用户提示：如果使用了异步API需要手动确认终止程序。）

**Comment by karoosnip** [comment]
这个是使用了okhttp的网络处理框架，它是有线程池管理，刚测试了下子线程执行完是会释放，只是不是立即释放。

**Comment by hopeful0** [comment]
恩，又测试了一下，确实会释放，开始测试的时候等待时间较短了。
