### ISSUE TITLE
一个这么小的库依赖这么多东西你们是认真的吗?

### ISSUE THREAD

**Issue by eritpchy** [yunify/qingstor-sdk-java#61]
一混淆就报错!!!一混淆就报错!!!一混淆就报错!!!
不说了 很不幸我已经接好了
我去改成Android SDK 去了

**Comment by eritpchy** [comment]
https://github.com/eritpchy/qingstor-sdk-android
https://github.com/eritpchy/qingstor-sdk-android/releases
untest!

**Comment by chengww5217** [comment]
抱歉，因为是 java 版本，未考虑太多安卓用户的需求。多谢提供。后期会慢慢完善。
